package com.toni.hosteleriatfg.util

const val STATUS_OK = 200
const val STATUS_OK_REGISTRO_CREADO = 201
const val STATUS_OK_CON_ERRORES = 202
const val STATUS_OK_VACIO = 204
const val STATUS_OK_INFO = 101
const val STATUS_ERROR_CLIENTE = 400
const val STATUS_ERROR_FORBIDDEN = 403
const val STATUS_PASSWORD_OUTDATED = 413
const val STATUS_USUARIO_SIN_PERMISOS = 414
const val STATUS_USUARIO_BLOQUEADO = 415
const val STATUS_USUARIO_NO_EXISTE = 416
const val STATUS_USUARIO_INVALID_PASSWORD = 417
const val STATUS_RESPONSE_REST = 450
const val STATUS_ERROR_CLIENTE_RECURSO_NO_ENCONTRADO = 404
const val STATUS_ERROR_CLIENTE_TIPO_MIME_NO_SOPORTADO = 415
const val STATUS_ERROR_SERVIDOR = 500